### ISSUE TITLE
Locked to Rack ~> 1.6

### ISSUE THREAD

**Issue by onewhaleid** [bjoernalbers/gollum-auth#2]
Line 25 of `gollum-auth.gemspec` states:

`  spec.add_dependency 'rack', '~> 1.6'`

The next release of `gollum` (5.x) uses `Rack 2.x`. Does `Rack 2.x` break `gollum-auth`?

**Comment by bjoernalbers** [comment]
Thanks for the heads-up!
I don't think that `rack 2.x` will break it but I have to check this before I'll change the gemspec.
Hang on...

**Comment by bjoernalbers** [comment]
Hmm, looks like Gollum 5 (or Rack 2) breaks Gollum::Auth. I've just tested with `gollum (5.0.1b)` and `rack (2.0.6)`. With the sample `config.ru` from this README users can create and update pages *without* authentication. I'll have to further dig into this...

**Comment by bjoernalbers** [comment]
I just released version 0.7.0 which works with Gollum 5 :-)
