### ISSUE TITLE
The committer is not the logged-in user

### ISSUE THREAD

**Issue by anordal** [bjoernalbers/gollum-auth#3]
I got the example config.ru file working by runnig this script in the same directory:

```
#!/usr/bin/env ruby
require 'sinatra/base'
```

I logged in as Rick Sanchez (as per the config), and made the first commit.

Result: The committer shown in `git show` is not Rick Sanchez, but whatever system user the daemon runs as.

I hope this is supposed to work! What can I do?

**Comment by anordal** [comment]
I see a pattern: Creating a new file uses the wrong user, but editing an existing file uses the right one. Deleting a file depends on which button is clicked.

I guess this must be a gollum issue, since it can't be *sometimes correct* without the right user details in the session.

**Comment by bjoernalbers** [comment]
Thanks for taking the time to invest and report this!

**Comment by pkulak** [comment]
There must be a bunch of new paths that this plugin is not aware of. I've noticed that if you allow read-only access, some operations don't get authed and are written to git as the anon user. If you auth reads and writes, that issue goes away.
